In [1]:
import pandas as pd

# Load Data

In [2]:
df = pd.read_csv("./data/Zeek_Data.csv")
df.head()

,resp_pkts,service,orig_ip_bytes,local_resp,missed_bytes,protocol,duration,conn_state,dest_ip,orig_pkts,...,orig_bytes,local_orig,datetime,history,resp_bytes,uid,src_port,ts,src_ip,mitre_attack_tactics
0,2,dns,186,False,0,udp,0.00228,SF,143.88.5.1,2,...,130.0,False,2022-02-10T03:58:29.979Z,Dd,130.0,CwO2bA321vyBxBjtxb,36073,1.644466e+09,143.88.5.12,Reconnaissance
1,2,dns,186,False,0,udp,0.00228,SF,143.88.5.1,2,...,130.0,False,2022-02-10T03:58:29.979Z,Dd,130.0,CwO2bA321vyBxBjtxb,36073,1.644466e+09,143.88.5.12,Reconnaissance
2,2,dns,186,False,0,udp,0.00228,SF,143.88.5.1,2,...,130.0,False,2022-02-10T03:58:29.979Z,Dd,130.0,CwO2bA321vyBxBjtxb,36073,1.644466e+09,143.88.5.12,Reconnaissance
3,2,dns,186,False,0,udp,0.00228,SF,143.88.5.1,2,...,130.0,False,2022-02-10T03:58:29.979Z,Dd,130.0,CwO2bA321vyBxBjtxb,36073,1.644466e+09,143.88.5.12,Reconnaissance
4,2,dns,186,False,0,udp,0.00228,SF,143.88.5.1,2,...,130.0,False,2022-02-10T03:58:29.979Z,Dd,130.0,CwO2bA321vyBxBjtxb,36073,1.644466e+09,143.88.5.12,Reconnaissance

# Overview of Data

In [3]:
df.describe()

,resp_pkts,orig_ip_bytes,missed_bytes,duration,orig_pkts,resp_ip_bytes,dest_port,orig_bytes,resp_bytes,src_port,ts
count,23003.000000,23003.000000,23003.0,2.233800e+04,23003.000000,23003.000000,23003.000000,22338.000000,22338.000000,23003.000000,2.300300e+04
mean,0.386602,149.897970,0.0,1.057302e+00,1.971569,32.735904,149.131157,95.402095,22.246933,46190.409642,1.642502e+09
std,0.819321,92.104006,0.0,3.913625e+00,0.856483,69.672363,1630.601391,68.926667,48.018928,10374.340191,9.946338e+05
min,0.000000,0.000000,0.0,9.536743e-07,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,1.641708e+09
25%,0.000000,134.000000,0.0,1.502037e-05,2.000000,0.000000,53.000000,78.000000,0.000000,40015.500000,1.641900e+09
50%,0.000000,138.000000,0.0,2.098083e-05,2.000000,0.000000,53.000000,82.000000,0.000000,46243.000000,1.642085e+09
75%,0.000000,158.000000,0.0,1.958132e-03,2.000000,0.000000,53.000000,102.000000,0.000000,53415.000000,1.642274e+09
max,5.000000,1439.000000,0.0,6.305099e+01,12.000000,656.000000,63331.000000,1271.000000,600.000000,65502.000000,1.644466e+09